<a href="https://colab.research.google.com/github/so-yeon-hwang/DataSciencePractice/blob/Data-Science-Class-(fall-2023)/linear_regression_and_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# torch / pytorch

In [3]:
import torch

In [4]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

print('x = ' , x)
print('y = ' , y)

x =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y =  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [10]:
# checking the size and rank
print('size : ' , x.size())
print('shape : ' ,x.shape)
print('rank : ', x.ndimension())

size :  torch.Size([3, 3])
shape :  torch.Size([3, 3])
rank :  2


In [13]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print("x0.shape:", x0.shape)
print("x1.shape:", x1.shape)
print("x2.shape:", x2.shape)

print("x0 =", x0)
print("x1 =", x1)
print("x2 =", x2)

print("x0.ndimension :", x0.ndimension())
print("x1.ndimension :", x1.ndimension())
print("x2.ndimension :", x2.ndimension())

x0.shape: torch.Size([1, 3, 3])
x1.shape: torch.Size([3, 1, 3])
x2.shape: torch.Size([3, 3, 1])
x0 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x1 = tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
x2 = tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
x0.ndimension : 3
x1.ndimension : 3
x2.ndimension : 3


In [17]:
# ERROR dimension

# original size of x == 3x3
# unsqueezing 3rd index of torch(=array) x cannot be executed, cause 3rd index means 4th dimension, but torch x does not have 4th dimension

# x3 = torch.unsqueeze(x, 3)
# x3

In [14]:
x = torch.tensor([[1, 2],
                  [3, 4]])
x3 = torch.unsqueeze(x, 0)
x3

tensor([[[1, 2],
         [3, 4]]])

In [15]:
x3.ndimension()

3

In [18]:
a = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])
a0 = torch.unsqueeze(a,0)
a0

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])

In [19]:
a3 = torch.unsqueeze(a,3)

In [20]:
a3

tensor([[[[1],
          [2]],

         [[3],
          [4]]],


        [[[5],
          [6]],

         [[7],
          [8]]]])

In [21]:
a2 = torch.unsqueeze(a,2)
a2

tensor([[[[1, 2]],

         [[3, 4]]],


        [[[5, 6]],

         [[7, 8]]]])

In [22]:
x0

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
x1 = torch.squeeze(x0)
x1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
torch.squeeze(x1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
x.shape

torch.Size([3, 3])

In [31]:
x.ndimension()

2

In [32]:
torch.squeeze(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
k = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
k

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
k.ndimension()

3

In [35]:
torch.squeeze(k)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
torch.squeeze(k)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
M = torch.tensor([[1],
                  [2],
                  [3]])
print(M.ndimension())
print(M.shape)

2
torch.Size([3, 1])


In [47]:
torch.squeeze(M).shape

torch.Size([3])

In [ ]:
# How can I know which tensor has 'one dimension' or not easily?
# >> using ### x.shape ### methhod and check the dimension

In [51]:
k = torch.tensor([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(k.shape)

k_ = torch.squeeze(k)
print(k_.shape)

torch.Size([1, 1, 1, 3, 3])
torch.Size([3, 3])


In [52]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
print(x)
x4 = x.view(9)
x5 = x.view(1,3,3)
print("x4 =", x4)
print("x5 =", x5)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x4 = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
x5 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [55]:
x = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])

w = torch.randn(1,2, dtype=torch.float)
b = torch.randn(3,1, dtype=torch.float)

result = torch.mm(x, torch.t(w)) + b

# torch.t(w) transpose
# torch.mm : matrix multiplication

print(result)

tensor([[-3.7303],
        [-2.9832],
        [-9.8772]])


# Linear Regression w/ Pytorch

In [67]:
import torch
x_train = torch.FloatTensor([[1,2], [3,2], [3,7], [1,1], [1,0]])
y_train = torch.FloatTensor([[4], [8], [23], [1], [-2]])
x_train, y_train

(tensor([[1., 2.],
         [3., 2.],
         [3., 7.],
         [1., 1.],
         [1., 0.]]),
 tensor([[ 4.],
         [ 8.],
         [23.],
         [ 1.],
         [-2.]]))

In [68]:
# making a linear graph / coef and y intercept
W = torch.rand(2,1)
b = torch.rand(1,1)

lr = 0.01
print(W,b)

tensor([[0.3173],
        [0.5554]]) tensor([[0.9252]])


In [66]:
for epoch in range(3001): # How many times gonna repeat
  W.requires_grad_(True)
  b.requires_grad_(True) # calculating Gradient  // requires grad True

    # making hypothesis
  h = torch.mm(x_train, W) + b

  # gap btw true values vs hypothesis values
  cost = ((y_train - h) ** 2).mean()

  cost.backward() # Gradient calcualating function
  with torch.no_grad() as grd : # pause _ gradient calculating
    W = W - lr * W.grad # updating W value : moving - direction
    b = b - lr * b.grad

  if epoch % 100 == 0: # checking the learning process
    print(epoch, cost.item(), W.squeeze(), b)

0 56.12255859375 tensor([0.7578, 1.1548]) tensor([[0.9719]])
100 1.9853897094726562 tensor([0.4530, 3.1709]) tensor([[-1.0017]])
200 0.9752392768859863 tensor([0.7705, 3.2102]) tensor([[-1.9338]])
300 0.5006149411201477 tensor([1.1050, 3.1606]) tensor([[-2.5282]])
400 0.2572683095932007 tensor([1.3568, 3.1163]) tensor([[-2.9460]])
500 0.13221482932567596 tensor([1.5387, 3.0835]) tensor([[-3.2445]])
600 0.06794806569814682 tensor([1.6693, 3.0599]) tensor([[-3.4584]])
700 0.03491976484656334 tensor([1.7629, 3.0429]) tensor([[-3.6118]])
800 0.01794600859284401 tensor([1.8300, 3.0308]) tensor([[-3.7217]])
900 0.00922287255525589 tensor([1.8782, 3.0221]) tensor([[-3.8005]])
1000 0.004739777650684118 tensor([1.9127, 3.0158]) tensor([[-3.8570]])
1100 0.002435889095067978 tensor([1.9374, 3.0113]) tensor([[-3.8975]])
1200 0.0012518439907580614 tensor([1.9551, 3.0081]) tensor([[-3.9265]])
1300 0.0006433373782783747 tensor([1.9678, 3.0058]) tensor([[-3.9473]])
1400 0.00033061258727684617 tensor([

In [70]:
x_test = torch.FloatTensor([[5,10]])
torch.mm(x_test, W) + b

tensor([[8.0655]])

In [71]:
test_result = torch.mm(x_test, W) + b
print(test_result.item())

# Therefore, if we put [[5,10]] in this graph, we'll get approximately value of 8 in this function.

8.065532684326172


# Linear Regression w/ Sklearn

In [72]:
from sklearn.linear_model import LinearRegression

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

lr = LinearRegression() # Model Generating
lr.fit(x, y) # Fitting / learning

print(lr.coef_, lr.intercept_)

[[2. 3.]] [-4.]


In [73]:
print(lr.predict([[5,10]]))

[[36.]]
