<a href="https://colab.research.google.com/github/so-yeon-hwang/DataSciencePractice/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [ ]:
x_data = np.array([0, 1, 2, 0, 0])
y_data = np.array([0, 0, 0, 1, 2])

In [ ]:
x_data = np.array([0, 1, 2, 0, 0])
y_data = np.array([0, 0, 0, 1, 2])

def polynomial_function(x,y,a,b,c,d,e,f,g):
    return a + b*x + c*y + d * x**2 + e*x*y + f * y**2

params, covariance = curve_fit(polynomial_function, x_data, y_data)
a, b, c, d, e, f = params

In [ ]:
import numpy as np

# 3x3 행렬 정의
matrix = np.array([[1, 0, 2],
                  [-3, 1, 4],
                  [2, -3, 4]])

# 역행렬을 구하기 전에 역행렬이 존재하는지 확인합니다.
determinant = np.linalg.det(matrix)
print('determinant :',determinant)

if determinant != 0:
    # 역행렬을 계산
    inverse_matrix = np.linalg.inv(matrix)
    print("역행렬:\n", inverse_matrix)
else:
    print("역행렬이 존재하지 않습니다. (행렬식이 0입니다.)")


determinant : 30.000000000000004
역행렬:
 [[ 5.33333333e-01 -2.00000000e-01 -6.66666667e-02]
 [ 6.66666667e-01 -4.75809868e-17 -3.33333333e-01]
 [ 2.33333333e-01  1.00000000e-01  3.33333333e-02]]


In [ ]:
determinant = np.linalg.det(matrix)

In [ ]:
determinant

30.000000000000004

In [ ]:
matrix = np.array([[1,2,-1],
                  [-4,-7,3],
                  [-2,-6,4]])

In [ ]:
determinant = np.linalg.det(matrix)

In [ ]:
determinant

0.0

In [ ]:
import numpy as np

# 3x1 열벡터
A = np.array([[2],
              [4],
              [1]])

# 1x3 행벡터
B = np.array([[1,3,2]])

# 외적 계산
C = np.dot(A, B)

print(C)

[[ 2  6  4]
 [ 4 12  8]
 [ 1  3  2]]
